name: python-deployment

run-name: ${{github.actor}} - ${{github.ref_name}} #Who starter Flow and from what branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
