name: CI
run-name: ${{github.actor}} initialized workflow

on:
  pull_request:

env:
  GITHUB_ACTIONS: "GitHub  Actions"

jobs:
  github-tast-job:

    runs-on: ubuntu-latest

    steps:
      - name: Show GITHUB_ACTIONS env
        run: echo "${{ env.GITHUB_ACTIONS }}"

      - name: Show repo name and branch name
        run: echo "repository name ${{github.repository.name}}\nbranch name ${{github.ref_name}}"

      - name: Show job trigger
        run: echo "job was triggered by ${{job.workflow_ref}}"